### ISSUE TITLE
CurveInterpolator works only with max. 8 samples

### ISSUE THREAD

**Issue by ruedigerO** [SignalK/SensESP#565] opened 2022-02-15 12:31 UTC
Is there a known limit for CurveInterpolator to 8 samples?
I tried via add_sample and if there are more than 8 samples the WebUI shows an error:
**Error retrieving configuration /tank/freshWaterSTBcurve: null is not an object (evaluating 'Object.keys(schema)')**

The same happens if I add the 9th sample vie WebUI and subsequently try to change something.

SensESP version: 2.1.1.

**Comment by mairas** [comment] 2022-02-16 14:35
This is a duplicate of Issue #415. Let's continue tracking the problem there.

**Closed by mairas** 2022-02-16 14:35 UTC
